##===- unittests/Data/Makefile -----------------------------*- Makefile -*-===##

LEVEL := ../..
TESTNAME := Data
USEDLIBS := kleaverExpr.a kleeBasic.a kleeData.a
LINK_COMPONENTS := support

include $(LEVEL)/Makefile.config
include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest

LIBS += -lstp 
